apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: trialrl5xsk.jfrog.io/dcimages-docker/devops-app:1.0.0
          ports:
            - containerPort: 3000